// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type StorageUserInitParameters struct {

	// (String) Description what the user is used for
	// Description what the user is used for
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// If set, access_key_id and secret_access_key will be populated into the state. Otherwise, an empty string will be written to the state. Please note that, since the credentials are only available once, manually regenerated credentials will not be synchronized into the state. If you must reroll the credentials, please consider recreating the user instead. If set, `access_key_id` and `secret_access_key` will be populated into the state. Otherwise, an empty string will be written to the state. Please note that, since the credentials are only available once, manually regenerated credentials will not be synchronized into the state. If you must reroll the credentials, please consider recreating the user instead.
	IncludeCredentials *bool `json:"includeCredentials,omitempty" tf:"include_credentials,omitempty"`

	// (String) The IAM permission document.
	// The IAM permission document.
	Permissions *string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// (String) Name of the user. The name must be unique inside your account.
	// Name of the user. The name must be unique inside your account.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type StorageUserObservation struct {

	// (String) Description what the user is used for
	// Description what the user is used for
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// If set, access_key_id and secret_access_key will be populated into the state. Otherwise, an empty string will be written to the state. Please note that, since the credentials are only available once, manually regenerated credentials will not be synchronized into the state. If you must reroll the credentials, please consider recreating the user instead. If set, `access_key_id` and `secret_access_key` will be populated into the state. Otherwise, an empty string will be written to the state. Please note that, since the credentials are only available once, manually regenerated credentials will not be synchronized into the state. If you must reroll the credentials, please consider recreating the user instead.
	IncludeCredentials *bool `json:"includeCredentials,omitempty" tf:"include_credentials,omitempty"`

	// (String) The IAM permission document.
	// The IAM permission document.
	Permissions *string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// (String) Name of the user. The name must be unique inside your account.
	// Name of the user. The name must be unique inside your account.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type StorageUserParameters struct {

	// (String) Description what the user is used for
	// Description what the user is used for
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// If set, access_key_id and secret_access_key will be populated into the state. Otherwise, an empty string will be written to the state. Please note that, since the credentials are only available once, manually regenerated credentials will not be synchronized into the state. If you must reroll the credentials, please consider recreating the user instead. If set, `access_key_id` and `secret_access_key` will be populated into the state. Otherwise, an empty string will be written to the state. Please note that, since the credentials are only available once, manually regenerated credentials will not be synchronized into the state. If you must reroll the credentials, please consider recreating the user instead.
	// +kubebuilder:validation:Optional
	IncludeCredentials *bool `json:"includeCredentials,omitempty" tf:"include_credentials,omitempty"`

	// (String) The IAM permission document.
	// The IAM permission document.
	// +kubebuilder:validation:Optional
	Permissions *string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// (String) Name of the user. The name must be unique inside your account.
	// Name of the user. The name must be unique inside your account.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// StorageUserSpec defines the desired state of StorageUser
type StorageUserSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     StorageUserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider StorageUserInitParameters `json:"initProvider,omitempty"`
}

// StorageUserStatus defines the observed state of StorageUser.
type StorageUserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        StorageUserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// StorageUser is the Schema for the StorageUsers API. Create a new user for the S3 API and assign permissions to the user. You can set IAM policy documents that adheres to the AWS Identity and Access Management (IAM) policy structure. The document defines permissions using a JSON-based format, following the official AWS specifications https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html for IAM policies. Example:
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,upjet-for-cancom}
type StorageUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permissions) || (has(self.initProvider) && has(self.initProvider.permissions))",message="spec.forProvider.permissions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   StorageUserSpec   `json:"spec"`
	Status StorageUserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// StorageUserList contains a list of StorageUsers
type StorageUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StorageUser `json:"items"`
}

// Repository type metadata.
var (
	StorageUser_Kind             = "StorageUser"
	StorageUser_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: StorageUser_Kind}.String()
	StorageUser_KindAPIVersion   = StorageUser_Kind + "." + CRDGroupVersion.String()
	StorageUser_GroupVersionKind = CRDGroupVersion.WithKind(StorageUser_Kind)
)

func init() {
	SchemeBuilder.Register(&StorageUser{}, &StorageUserList{})
}
