apiVersion: upjet-for-cancom.m.crossplane.nvst.cloud/v1beta1
kind: ProviderConfig
metadata:
  name: cancom
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: cancom-creds
      namespace: crossplane-system
      key: credentials
